---
# Source: log-aggregation-system/templates/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: log-aggregation-system
  labels:
    helm.sh/chart: log-aggregation-system-0.1.0
    app.kubernetes.io/name: log-aggregation-system
    app.kubernetes.io/instance: log-aggregation-system
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: log-aggregation-system
      app.kubernetes.io/instance: log-aggregation-system
---
# Source: log-aggregation-system/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: log-aggregation-system
  labels:
    helm.sh/chart: log-aggregation-system-0.1.0
    app.kubernetes.io/name: log-aggregation-system
    app.kubernetes.io/instance: log-aggregation-system
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: log-aggregation-system/templates/configmap-otel.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: log-aggregation-system-otel
  labels:
    helm.sh/chart: log-aggregation-system-0.1.0
    app.kubernetes.io/name: log-aggregation-system
    app.kubernetes.io/instance: log-aggregation-system
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
      memory_limiter:
        check_interval: 1s
        limit_mib: 256

    exporters:
      logging:
        loglevel: info
      otlp/jaeger:
        endpoint: localhost:4317
        tls:
          insecure: true
      prometheus:
        endpoint: "0.0.0.0:8889"

    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      pprof:
        endpoint: :1888
      zpages:
        endpoint: :55679

    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging, otlp/jaeger]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging, prometheus]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging]
---
# Source: log-aggregation-system/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: log-aggregation-system
  labels:
    helm.sh/chart: log-aggregation-system-0.1.0
    app.kubernetes.io/name: log-aggregation-system
    app.kubernetes.io/instance: log-aggregation-system
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
data:
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  OTEL_ENABLED: "true"
  OTEL_SERVICE_NAME: "log-aggregation-system"
  STORAGE_BACKEND: "elasticsearch"
  ELASTICSEARCH_INDEX: "logs"
---
# Source: log-aggregation-system/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-aggregation-system-elasticsearch
  labels:
    helm.sh/chart: log-aggregation-system-0.1.0
    app.kubernetes.io/name: log-aggregation-system
    app.kubernetes.io/instance: log-aggregation-system
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# Source: log-aggregation-system/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: log-aggregation-system
  labels:
    helm.sh/chart: log-aggregation-system-0.1.0
    app.kubernetes.io/name: log-aggregation-system
    app.kubernetes.io/instance: log-aggregation-system
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
    - port: 9200
      targetPort: es-http
      protocol: TCP
      name: elasticsearch
    - port: 4317
      targetPort: otlp-grpc
      protocol: TCP
      name: otlp-grpc
    - port: 4318
      targetPort: otlp-http
      protocol: TCP
      name: otlp-http
    - port: 8888
      targetPort: metrics
      protocol: TCP
      name: otel-metrics
    - port: 8889
      targetPort: prom-export
      protocol: TCP
      name: otel-prom-exp
    - port: 13133
      targetPort: health
      protocol: TCP
      name: otel-health
  selector:
    app.kubernetes.io/name: log-aggregation-system
    app.kubernetes.io/instance: log-aggregation-system
---
# Source: log-aggregation-system/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-aggregation-system
  labels:
    helm.sh/chart: log-aggregation-system-0.1.0
    app.kubernetes.io/name: log-aggregation-system
    app.kubernetes.io/instance: log-aggregation-system
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: log-aggregation-system
      app.kubernetes.io/instance: log-aggregation-system
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8000"
        prometheus.io/scrape: "true"
        checksum/config: 1c3cb88041d65952258f00ea0c388d1ad19e7222a190ca3643ae1957ff1d6c00
      labels:
        helm.sh/chart: log-aggregation-system-0.1.0
        app.kubernetes.io/name: log-aggregation-system
        app.kubernetes.io/instance: log-aggregation-system
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: log-aggregation-system
      securityContext:
        fsGroup: 1000
      initContainers:
        # Wait for Elasticsearch to be ready
        - name: wait-for-elasticsearch
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z localhost 9200; do echo waiting for elasticsearch; sleep 2; done']
      containers:
        # Main Log Aggregation Application
        - name: log-aggregator
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsNonRoot: true
            runAsUser: 1000
          image: "log-aggregation-system:1.0.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: LOG_LEVEL
              value: "INFO"
            - name: LOG_FORMAT
              value: "json"
            - name: OTEL_ENABLED
              value: "true"
            - name: OTEL_SERVICE_NAME
              value: "log-aggregation-system"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://localhost:4317"
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
            - name: STORAGE_BACKEND
              value: "elasticsearch"
            - name: ELASTICSEARCH_URL
              value: "http://localhost:9200"
            - name: ELASTICSEARCH_INDEX
              value: "logs"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi

        # Elasticsearch
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
          ports:
            - name: es-http
              containerPort: 9200
              protocol: TCP
          env:
            - name: discovery.type
              value: "single-node"
            - name: xpack.security.enabled
              value: "false"
            - name: xpack.security.enrollment.enabled
              value: "false"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          livenessProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 3
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
          resources:
            limits:
              cpu: 2000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi

        # OpenTelemetry Collector
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.92.0
          args: ["--config=/etc/otel-collector-config.yaml"]
          ports:
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
            - name: metrics
              containerPort: 8888
              protocol: TCP
            - name: prom-export
              containerPort: 8889
              protocol: TCP
            - name: health
              containerPort: 13133
              protocol: TCP
          volumeMounts:
            - name: otel-config
              mountPath: /etc/otel-collector-config.yaml
              subPath: otel-collector-config.yaml
          livenessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi

      volumes:
        - name: otel-config
          configMap:
            name: log-aggregation-system-otel
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: log-aggregation-system-elasticsearch
---
# Source: log-aggregation-system/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "log-aggregation-system-test-connection"
  labels:
    helm.sh/chart: log-aggregation-system-0.1.0
    app.kubernetes.io/name: log-aggregation-system
    app.kubernetes.io/instance: log-aggregation-system
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['log-aggregation-system:']
  restartPolicy: Never
